# frozen_string_literal: true

source 'http://rubygems.org'

gem 'activerecord'
gem 'bcrypt'
gem 'pg'
gem 'rack-contrib'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib', require: false

group :test do
  gem 'byebug'
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'faker'
  gem 'rack-test'
  gem 'rspec'
end
