# frozen_string_literal: true

source 'http://rubygems.org'

gem 'activerecord'
gem 'bcrypt'
gem 'pg'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.3.6'

group :test do
  gem 'byebug'
  gem 'database_cleaner'
  gem 'rack-test'
  gem 'rspec'
end
